### ISSUE TITLE
Voice_commands

### ISSUE THREAD

**Issue by Nehuyaneponimau** [wootguy/voice_commands#10]
How to upload, what to write, where to put it? More details, I don't understand! 
Where to save Cvars do you need amx mod??
HELP I'M A NOOB

**Comment by wootguy** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=605607881

and check the readme in the [release .zip](https://github.com/wootguy/voice_commands/releases/tag/v13). No amxx needed.
