### ISSUE TITLE
New version crashes the game

### ISSUE THREAD

**Issue by Cads182** [wootguy/voice_commands#7]
I'm triying to run the new version (default version, not edited) and I can't, game crash with the folowing message:
Fatal error Sven Co-op has crashed unexpectedly. A crash report has been submitted automatically. we apogolize for the inconvenience.

I was able to reload the plugin before it crash and got this on AS logs:
```ERROR: d:/steam/steamapps/common/sven co-op/svencoop/scripts/plugins/voice_commands/VoiceCommands.as (91, 94) : No matching symbol 'CHAN_NETWORKVOICE_BASE'
ERROR: d:/steam/steamapps/common/sven co-op/svencoop/scripts/plugins/voice_commands/VoiceCommands.as (91, 94) : Can't implicitly convert from 'int' to 'SOUND_CHANNEL&'.
ERROR: d:/steam/steamapps/common/sven co-op/svencoop/scripts/plugins/voice_commands/VoiceCommands.as (351, 11) : Multiple matching signatures to 'CBaseMonster::StartPlayerFollowing(CBasePlayer@&)'
ERROR: d:/steam/steamapps/common/sven co-op/svencoop/scripts/plugins/voice_commands/VoiceCommands.as (353, 11) : Multiple matching signatures to 'CBaseMonster::StopPlayerFollowing(const bool)'
ERROR: d:/steam/steamapps/common/sven co-op/svencoop/scripts/plugins/voice_commands/VoiceCommands.as (441, 13) : Use of uninitialized global variable 'channels'.
ERROR: d:/steam/steamapps/common/sven co-op/svencoop/scripts/plugins/voice_commands/VoiceCommands.as (442, 10) : Use of uninitialized global variable 'channels'.
ERROR: d:/steam/steamapps/common/sven co-op/svencoop/scripts/plugins/voice_commands/VoiceCommands.as (449, 24) : Use of uninitialized global variable 'channels'.
ERROR: d:/steam/steamapps/common/sven co-op/svencoop/scripts/plugins/voice_commands/VoiceCommands.as (450, 41) : Use of uninitialized global variable 'channels'.
ERROR: d:/steam/steamapps/common/sven co-op/svencoop/scripts/plugins/voice_commands/VoiceCommands.as (479, 41) : Use of uninitialized global variable 'channels'.
```

**Comment by wootguy** [comment]
Try the script in the [master branch](https://github.com/wootguy/voice_commands/blob/master/VoiceCommands.as). A crash related to monster following was fixed recently. It's weird that you can't even load it though. That might be a different problem.

**Comment by Cads182** [comment]
I'm trying to load that one actually and crashes the game :cry:

**Comment by wootguy** [comment]
I don't understand how your server is getting compilation errors but not mine. I guess you could try casting [the values here](https://github.com/wootguy/voice_commands/blob/master/VoiceCommands.as#L99) to SOUND_CHANNEL. Those values are already the SOUND_CHANNEL type though so the error really doesn't make sense.

Disabling monster following with `vc.monster_reactions 0` might help with the other errors.

**Comment by Cads182** [comment]
I'm trying to run the plugin on listen server, I edit that line as you tell and now the game doesn't crash but got the same message on logs.

**Comment by wootguy** [comment]
Maybe the wrong plugin path is being used if the same errors are showing up. Once I had to rename a script to get it to run, even though the new script had exactly the same content. Can't remember if it was crashing or not.

**Comment by Cads182** [comment]
Now it works, I change the folder name to voice_command instead of voice_commands and I edit plugin_path
and <SOUND_CHANNEL> channels is back to normal.

**Comment by wootguy** [comment]
Ok, so I wasn't going crazy. Somehow the game gets into this state where you can't use a script anymore until it's renamed/moved. I tried using an old script that was doing this to me last year and it's working now, so I guess this would eventually fix itself. There's probably a hidden file cache somewhere that needs to be cleaned.

**Comment by Cads182** [comment]
Seems the case, thanks for your time and help :+1:
