### ISSUE TITLE
ERROR: Failed to add include file '../SoundCache/StartSoundMsg'!

### ISSUE THREAD

**Issue by danylopez123** [wootguy/voice_commands#8]
I first downloaded the release version then the source code to overwrite them with the recent version of it.
However, i checked why it was not working and in the AngelScript log file, this is what it happens:

ERROR: Failed to add include file '../SoundCache/StartSoundMsg'!
ERROR: Failed to add plugin 'VoiceCommands'!

**Comment by wootguy** [comment]
You'll need the SoundCache plugin installed if you want to use the lastest code.
https://github.com/wootguy/SoundCache

**Comment by danylopez123** [comment]
That fixed the problem, thanks!
